import os
from pathlib import Path

import numpy as np

DATA_FILE = Path("data/2026052521500100dBZ.vol.nc4")
OUTPUT_DIR = Path("output")
MPLCONFIG_DIR = OUTPUT_DIR / ".matplotlib-cache"
PRODUCT_TYPE = "cmax"
PPI_ELEVATION_DEG = 0.5
CAPPI_HEIGHT_KM = 2.0
PCAPPI_HEIGHT_KM = 2.0
SRI_ELEVATION_DEG = 0.5
SRI_ZR_A = 200.0
SRI_ZR_B = 1.6
SRI_MIN_DBZ = 10.0
SRI_MAX_DBZ = 55.0
KECAMATAN_SHP_FILES = [
    Path("shp/WADMPR_Jawa_Tengah.shp"),
    Path("shp/WADMPR_Jawa_Barat.shp"),
    Path("shp/WADMPR_Daerah_Istimewa_Yogyakarta.shp"),
    Path("shp/WADMPR_Nusa_Tenggara_Timur.shp"),
]
KECAMATAN_NAME_FIELD = "WADMKC"
SHOW_KECAMATAN_LABELS = True
SHOW_KECAMATAN_BOUNDARIES = False
KECAMATAN_LABEL_FONT_SIZE = 4.0
KECAMATAN_LABEL_COLOR = "#202020"
KECAMATAN_LABEL_ALPHA = 0.72
KECAMATAN_LABEL_OUTLINE_COLOR = "white"
KECAMATAN_LABEL_OUTLINE_WIDTH = 1.4
KECAMATAN_LABEL_COLLISION_PADDING_PX = 3
KECAMATAN_LABEL_MIN_DISTANCE_PX = 24
KECAMATAN_LABEL_MAX_COUNT = 150
KECAMATAN_LABEL_GRID_CELL_PX = 20
KECAMATAN_LABEL_MAX_PER_GRID_CELL = 1
KECAMATAN_BOUNDARY_COLOR = "#222222"
KECAMATAN_BOUNDARY_LINEWIDTH = 0.25
KECAMATAN_BOUNDARY_ALPHA = 0.35
WRITE_CMAX_IMAGE = True
WRITE_CMAX_NETCDF = False
WRITE_ELEVATION_GIF = False
OUTPUT_CMAX_IMAGE_NAME = "cmax.png"
OUTPUT_CMAX_NETCDF_NAME = "cmax.nc"
OUTPUT_ELEVATION_GIF_NAME = "elevations.gif"

GRID_RESOLUTION_KM = 0.05
DISPLAY_MIN_DBZ = 10.0
DISPLAY_SMOOTH_SIGMA = 0.0

PLOT_RANGE_X_KM = 80.0
PLOT_RANGE_Y_KM = 60.0
CMAX_RANGE_X_KM = 80.0
CMAX_RANGE_Y_KM = 60.0
CMAX_MIN_HEIGHT_KM = 0.0
CMAX_MAX_HEIGHT_KM = 25.0

RADAR_OVERLAY_ALPHA = 0.5
ELEVATION_GIF_FRAME_MS = 650
CMAX_IMAGE_DPI = 300
ELEVATION_GIF_DPI = 120
FIGURE_SIZE = (13, 8.0)
FIGURE_GRID_WIDTH_RATIOS = (6.9, 1.6)
FIGURE_GRID_WSPACE = 0.02
FIGURE_SUBPLOTS_ADJUST = {
    "left": 0.04,
    "right": 0.99,
    "top": 0.94,
    "bottom": 0.05,
}
MAP_FACE_COLOR = "#d8edf3"
RADAR_IMAGE_ZORDER = 3
BASEMAP_TILE_ZORDER = 0
KECAMATAN_BOUNDARY_ZORDER = 6
KECAMATAN_LABEL_ZORDER = 7

TITLE_FONT_SIZE = 10

SIDE_PANEL_LEGEND_X = 0.05
SIDE_PANEL_LEGEND_Y = 0.40
SIDE_PANEL_LEGEND_WIDTH = 0.32
SIDE_PANEL_LEGEND_HEIGHT = 0.34
SIDE_PANEL_TEXT_Y = 0.365
SIDE_PANEL_VALUE_WRAP_WIDTH = 27
SIDE_PANEL_LOGO_PATH = Path("assets/logo-bmkg.png")
SIDE_PANEL_LOGO_X = 0.55
SIDE_PANEL_LOGO_Y = 0.985
SIDE_PANEL_LOGO_WIDTH = 0.18
SIDE_PANEL_LOGO_HEIGHT = 0.095
SIDE_PANEL_LOGO_RESAMPLE = "lanczos"
SIDE_PANEL_LOGO_INTERPOLATION = "none"
SIDE_PANEL_LOGO_ZORDER = 3
SIDE_PANEL_HEADER_TITLE_TEXT = "Stasiun Meteorologi Kelas II Tunggul Wulung Cilacap"
SIDE_PANEL_HEADER_SUBTITLE_TEXT = None
SIDE_PANEL_HEADER_TITLE_WRAP_WIDTH = 20
SIDE_PANEL_HEADER_SUBTITLE_WRAP_WIDTH = 24
SIDE_PANEL_HEADER_LINE_STEP = 0.027
SIDE_PANEL_HEADER_SUBTITLE_GAP = 0.012
SIDE_PANEL_TITLE_X = 0.55
SIDE_PANEL_TITLE_Y = 0.875
SIDE_PANEL_TITLE_FONT_SIZE = 9
SIDE_PANEL_TIME_X = 0.55
SIDE_PANEL_TIME_Y = 0.825
SIDE_PANEL_TIME_FONT_SIZE = 8
SIDE_PANEL_KEY_X = 0.02
SIDE_PANEL_VALUE_X = 0.43
SIDE_PANEL_ROW_FONT_SIZE = 5.8
SIDE_PANEL_ROW_BASE_STEP = 0.014
SIDE_PANEL_ROW_LINE_STEP = 0.009
LEGEND_BORDER_LINEWIDTH = 0.8
LEGEND_TICK_LENGTH = 0.025
LEGEND_LABEL_GAP = 0.05
LEGEND_LABEL_FONT_SIZE = 8

USE_BASEMAP_TILES = os.getenv("USE_BASEMAP_TILES", "false").lower() == "true"
BASEMAP_TILE_PROVIDER = "MapTiler Satellite"
BASEMAP_TILE_URL = os.getenv("MAPTILER_TILE_URL", "")
BASEMAP_TILE_ZOOM = 10
BASEMAP_TILE_CACHE_DIR = Path(os.getenv("BASEMAP_TILE_CACHE_DIR", "cache/basemap"))
BASEMAP_TILE_USER_AGENT = "BMKG-Cilacap-Radar-CMAX/1.0"
BASEMAP_TILE_INTERPOLATION = "bilinear"
BASEMAP_ATTRIBUTION_TEXT = "© Radar contributors"
BASEMAP_ATTRIBUTION_X = 0.01
BASEMAP_ATTRIBUTION_Y = 0.01
BASEMAP_ATTRIBUTION_FONT_SIZE = 7
BASEMAP_ATTRIBUTION_ZORDER = 10
BASEMAP_ATTRIBUTION_BOX_ALPHA = 0.65
BASEMAP_ATTRIBUTION_BOX_PAD = 1.5

GRIDLINE_LINEWIDTH = 0.4
GRIDLINE_COLOR = "black"
GRIDLINE_ALPHA = 0.35
GRIDLINE_STYLE = "--"
GRIDLINE_LABEL_FONT_SIZE = 8

RADAR_MARKER_SIZE = 5
RADAR_MARKER_FACE_COLOR = "red"
RADAR_MARKER_EDGE_COLOR = "white"
RADAR_MARKER_EDGE_WIDTH = 1.5
RADAR_MARKER_ZORDER = 10
SHOW_RANGE_RINGS = True
RANGE_RING_RADII_KM = (25, 50, 75)
RANGE_RING_COLOR = "#333333"
RANGE_RING_LINEWIDTH = 0.65
RANGE_RING_ALPHA = 0.7
RANGE_RING_LABEL_FONT_SIZE = 6
SCALE_BAR_KM = 25
SCALE_BAR_X = 0.06
SCALE_BAR_Y = 0.045
SCALE_BAR_WIDTH_AXES = 0.22
SCALE_BAR_COLOR = "black"
SCALE_BAR_LINEWIDTH = 2.0
SCALE_BAR_FONT_SIZE = 7

FOOTER_TEXT = "Copyright © 2026 satrio.dev. All rights reserved."
FOOTER_X = 0.006
FOOTER_Y = 0.006
FOOTER_FONT_SIZE = 7
FOOTER_COLOR = "#555555"

TRANSPARENT_COLOR = (1.0, 1.0, 1.0, 0.0)
REFLECTIVITY_OVER_COLOR = "#ff00e8"

RANGE_UNIT_TO_METER = 1000.0
AZIMUTH_FULL_CIRCLE_DEG = 360.0
RAINBOW_ANGLE_SCALE = 65536.0
RAINBOW_DEFAULT_MIN_VALUE = "-31.5"
RAINBOW_DEFAULT_MAX_VALUE = "95.5"
MISSING_VALUE_THRESHOLD = -1000.0
MIN_SAMPLE_WEIGHT = 0.05

REFLECTIVITY_BOUNDS = np.array(
    [-10, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64],
    dtype=float,
)
REFLECTIVITY_LABELS = np.array(
    [-10, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64],
    dtype=float,
)
REFLECTIVITY_COLORS = [
    "#d9d9d9",
    "#9ff7f1",
    "#63cfea",
    "#2f9df4",
    "#2362f1",
    "#a8ff00",
    "#7ed800",
    "#55a600",
    "#2f7600",
    "#004800",
    "#ffff00",
    "#ffbf2e",
    "#ff8a16",
    "#ff4b00",
    "#b80000",
    "#ff00e8",
]

RAIN_RATE_BOUNDS = np.array(
    [0.1, 0.5, 1, 2, 5, 10, 20, 30, 50, 75, 100],
    dtype=float,
)
RAIN_RATE_LABELS = np.array(
    [0.1, 0.5, 1, 2, 5, 10, 20, 30, 50, 75, 100],
    dtype=float,
)
RAIN_RATE_COLORS = [
    "#d9d9d9",
    "#9ff7f1",
    "#63cfea",
    "#2f9df4",
    "#2362f1",
    "#a8ff00",
    "#55a600",
    "#ffff00",
    "#ffbf2e",
    "#ff4b00",
    "#b80000",
]
RAIN_RATE_OVER_COLOR = "#ff00e8"
